import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Layers3, BookOpen, User, Book } from "lucide-react";
import ButtonLogout from "./(home)/components/button-logout";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const inter=Inter({subsets:["latin"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <section>
            <nav className="border-b border-muted p-5">
                <span className="flex flex-row items-center justify-between">
                    <span className="font-bold text-primary">
                        NewsGo
                    </span>
                </span>
            </nav>
        </section>

        <section className="flex flex-row gap-5 item-start flex-nowrap">
            <section className="grow-0 w-[20%] h-screen shadow p-5 space-y-5">
                <Button variant={"ghost"} asChild className="w-full justify-start">
                        <Link href={"/dashbord"}>Dashboard</Link>
                </Button>

                <div className="space-y-2">
                    <div className="uppercase text-xs font-bold">
                        Master Data
                    </div>

                    <Button variant={"ghost"} asChild className="w-full justify-start">
                        <Link href={""}>
                            <Layers3 className="mr-2 w-4 h4"/>
                            Kategori
                        </Link>
                    </Button>


                    <Button variant={"ghost"} asChild className="w-full justify-start">
                        <Link href={""}>
                            <BookOpen className="mr-2 w-4 h4"/>
                            Konten
                        </Link>
                    </Button>

                    <Button variant={"ghost"} asChild className="w-full justify-start">
                        <Link href={""}>
                            <User className="mr-2 w-4 h4"/>
                            Pengguna
                        </Link>
                    </Button>
                </div>

                <ButtonLogout/>
            </section>   
        </section>
        {children}
      </body>
    </html>
  );
}
